### ISSUE TITLE
False-Positive result when checking for Unused Parameters

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#359]
**Current Behavior**
False-Positive Violation when having two parameters with different parameter id (`definition.parameters.${parameter_id}`), but the same parameter name (`definition.parameters.${parameter_id}.name.${parameter_name}`)

The behavior is incorrect since the usage of the parameter can be verified only by the usage of the link to the parameter. And this is done via `parameter_id`.

**How to Reproduce**
Part of the API definition to reproduce the behavior:
```
parameters:
  identifier_type:
    name: identifier_type
    description: Specifies the type of the customer identifier.
    in: path
    type: string
    x-extensible-enum:
      - customer_hash
      - cookie_id
      - fullvisitorid
      - client_id
      - idfa
    required: true

  target_identifier_type:
    name: identifier_type
    description: Specifies what type of customer identifiers to be returned
    in: query
    type: string
    x-extensible-enum:
      - customer_hash
      - cookie_id
      - fullvisitorid
      - client_id
      - idfa
    required: false

paths:
  /identifier-types/{identifier_type}/source-ids/{source_identifier}:
    get:
      tags:
        - id-mappings
      description: List of identifiers associated with the source id.
      parameters:
        - $ref: '#/parameters/identifier_type'
        - $ref: '#/parameters/source_identifier'
        - $ref: '#/parameters/target_identifier_type'
      responses:
        200:
          description: The identifiers associated with the source id.
          schema:
            $ref: '#/definitions/IdMappingResults'
        401:
          description: User is not authenticated
        403:
          description: User is not authorized
        404:
          description: Identifier is not found
          schema:
            $ref: '#definitions/Problem'
      security:
        - oauth2:
          - 'cross-device-graph-service.read'
```

**Expected Behavior**
Identifying of the unused parameters should be done based on the `parameter_id` instead of `parameter_name`.

**Comment by innokenty** [comment]
I don't think the specified case is a valid swagger doc. `parameter.name` is the essential field that defines which parameter is which.

### Proof №1: check the docs
Open this link and scroll a tiny bit up, because the header covers the title: https://swagger.io/specification/#fixed-fields-45
That's the spec for the parameters, and it says the `name` is required and only it identifies the parameter's name. Not the tagname above.
![screen shot 2017-07-24 at 15 13 40](https://user-images.githubusercontent.com/4004229/28524926-c0902a8a-7082-11e7-92a1-5dde7e630dfe.png)


### Proof №2: try the presented specification
Go here: http://editor.swagger.io and paste the api definition, presented in this issue above (simplified):
```yaml
swagger: '2.0'
info:
  title: Product Service
  version: 1.0.0

paths:
  '/identifier-types/{identifier_type}/source-ids':
    get:
      parameters:
        - $ref: '#/parameters/identifier_type'
        - $ref: '#/parameters/target_identifier_type'
      responses:
        '200':
          description: The identifiers associated with the source id.
parameters:
  identifier_type:
    name: identifier_type
    description: Specifies the type of the customer identifier.
    in: path
    type: string
    required: true
  target_identifier_type:
    name: identifier_type
    description: Specifies what type of customer identifiers to be returned
    in: query
    type: string
    required: false
```

In the panel to the right, that shows the generated UI you can see that there is only one parameter: `target_identifier_type` is omitted. But if you change it to `name: target_identifier_type` - it appears in the UI as it should.

### Proof №3: Java ignores it
In tests we do `SwaggerParser().read("api_definition.json")`
When I insert the presented example definition above into file, I can see in debug mode that the get operation node of the parsed swagger doc contains only 2 parameters, not 3. I think it matches them by names and therefore overrides the conflicting one.

## Conclusion
Any thoughts? I think it's not a valid spec and the issue should be closed.

**Comment by maxim-tschumak** [comment]
@innokenty Thank you for the research! Closing the issue.
