### ISSUE TITLE
Incorrectly rejecting "official" RateLimit headers

### ISSUE THREAD

**Issue by conorclifford** [zalando-incubator/zally#572]
Validating API that contains the following:

```yaml
responses:
  TooManyRequests:
    description: Too many requests
    schema:
      $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
    headers:
      X-RateLimit-Limit:
        description: The maximum number of requests that the client is allowed to make in this window
        type: integer
      X-RateLimit-Remaining:
        description: The number of requests allowed in the current window
        type: integer
      X-RateLimit-Reset:
        description: The relative time in seconds when the rate limit window will be reset
        type: integer
```

is rejected for the following reason:

```
MUST – Use Hyphenated HTTP Headers
Header names should be hyphenated

Rule: http://zalando.github.io/restful-api-guidelines/#131

Paths:

/products/{tier} X-RateLimit-Limit
/products/{tier} X-RateLimit-Remaining
/products/{tier} X-RateLimit-Reset
```

Note, these headers are correct, as described in the [API guidelines](http://zalando.github.io/restful-api-guidelines/#153).

**Comment by roxspring** [comment]
Seems we have a bunch of rules conspiring to conflict with each other:
* [Must: Use Hyphenated HTTP Headers [131]](http://zalando.github.io/restful-api-guidelines/#131)
** Spectacularly avoids having any description beyond the heading (maybe somebody within Zalando should try and get that clarified?)
** Literal interpretation implies that any header that contains a hypen would pass this rule.
** `HyphenateHttpHeadersRule` uses `PatternUtil.isHyphenated(header)` which appears to also enforce rule 132.
* [Should: Prefer Hyphenated-Pascal-Case for HTTP header Fields [132]](http://zalando.github.io/restful-api-guidelines/#132)
** `PascalCaseHttpHeadersRule` uses `PatternUtil.isHypehnatedPascalCase(header)` which appears equivalent to `PatternUtil.isHyphenated(header)` but via a different route.
* [May: Use Standardized Headers [133]](http://zalando.github.io/restful-api-guidelines/#133)
** Arguably should be relevant since the X-RateLimit headers are defacto standardized
** But isn't actually validated by any rule implementation yet anyway.
* [Must: Use 429 with Headers for Rate Limits [153]](http://zalando.github.io/restful-api-guidelines/#153)
** Requires X-RateLimit headers to be used, even though they're not Hyphenated-Pascal-Case or technically exempted by the use of Standardized Headers.
** Implemented in `Use429HeaderForRateLimitRule` which appears to do the right thing.

Suggest this is fixed by:
1. Relax `PatternUtil.isHyphenated(header)` to do just what it's name suggests and stop `HyphenateHttpHeadersRule` being over aggressive
2. White list the X-RateLimit header trio to in rules-config.conf to relax `PascalCaseHttpHeadersRule`
