### ISSUE TITLE
Use only 1 JSON Library in Zally CLI

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#70]
Currently we are using 2 JSON libraries in CLI tool. This leads to some inefficient data format transformations like:

https://github.com/zalando-incubator/zally/blob/master/cli/src/main/java/de/zalando/zally/cli/YamlReader.java#L22

Goal: Minimise amount of JSON libraries to 1

**Comment by fmueller** [comment]
I did some research in the Internet for this code snippet. It seems to be - and that's pretty weird - only way to have simple translation from yaml to json in Java, regardless of used data structures.

Because of this I propose to stick to org.json as JSON library and remove the other one.

What do you think? Maybe you can find a more elegant way to convert from yaml to json in Java.

**Comment by netme** [comment]
I still haven't done any research, but I will take a look on it, maybe I will find something. In worst case we will use `org.json` :-)

**Comment by netme** [comment]
I have checked `minimaljson` library which we are mostly using in CLI. Seems to be no way to do easy conversion `yaml` -> `json` using this library. So the option we have is to use `org.json`. Most probably the first good step is to abstract out the Json library usage from the main business logic and then slowly switch to `org.json`.

**Comment by fmueller** [comment]
As there is not so much business logic, I would just replace json calls with `org.json` calls.

**Comment by netme** [comment]
I think we are still relying a bit on `minimal-json` data structures, but I will try to find a good solution. Most probably `minimal-json` was not the best choice that time.
